apiVersion: apps/v1
kind: Deployment
metadata:
  name: safesecrets-controller
  namespace: safesecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safesecrets-controller
  template:
    metadata:
      labels:
        app: safesecrets-controller
    spec:
      serviceAccountName: safesecrets-controller-sa
      containers:
        - name: safesecrets-controller
          image: janbakkerhch/safesecrets-controller:1.0.0

