apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ss-configuration
data:
  master.conf: |
    maxmemory 400mb
    appendonly no
    dir /data
    bind 0.0.0.0
  slave.conf: |
    slaveof redis-ss-0.redis-service 6379
